name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Telegram
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_URL: https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
      ANDROID_BUILD_TOOLS_VERSION: 33.0.0
      ANDROID_HOME: /usr/local/android-sdk-linux
      ANDROID_NDK_VERSION: 21.4.7075529
      ANDROID_VERSION: 33
      ANDROID_NDK_HOME: ${ANDROID_HOME}/ndk/${ANDROID_NDK_VERSION}/
      PATH: ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
      
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Download Android SDK
      run: |
        mkdir "$ANDROID_HOME" .android && cd "$ANDROID_HOME"
        curl -o sdk.zip $ANDROID_SDK_URL && unzip sdk.zip
        rm sdk.zip
        
    - name: aaa
      run: |
        yes | ${ANDROID_HOME}/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --update
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;30.0.3" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platforms;android-${ANDROID_VERSION}" "platform-tools" "ndk;$ANDROID_NDK_VERSION"
